---
name: Deploy to Production

"on":
  workflow_call:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY:
        description: The SSH private key used by Ansible
        required: true
      ANSIBLE_VAULT_PASSWORD_PROD:
        description: The vault prod password used by Ansible
        required: true
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
      extra-ansible-options:
        description: Extra ansible-playbook options
        required: false

env:
  # renovate: datasource=pypi depName=ansible-core
  ANSIBLE_CORE_VERSION: 2.13.1

jobs:
  deploy-to-production:
    name: Deploy to production
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ (github.event.inputs || inputs).version }}

      - name: Set up Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb # tag=v4.0.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.10.5

      - name: Install ansible
        run: pip install ansible-core=="$ANSIBLE_CORE_VERSION"

      - name: Run playbook
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@671974ed60e946e11964cb0c26e69caaa4b1f559 # tag=v2.5.0
        with:
          directory: ansible
          playbook: apply-configuration.yml
          requirements: requirements.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          options: ${{ github.event.inputs.extra-ansible-options }}
        env:
          ANSIBLE_VAULT_PASSWORD_PROD: |
            ${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}
